### ISSUE TITLE
Spawn corals in a river without water inside

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#18]
In the rivers in the mountain, corals spawn without water and it looks strange
![2021-04-25_13 35 56](https://user-images.githubusercontent.com/68811273/116478439-bd4dab00-a886-11eb-9abf-31343422fc97.png)

**Server and Plugin Informations**
 - Installed plugins: Iris
 - Last build github
 - PaperSpigot 1.16.5 #613]:
 - Operating System (if applicable): 7 gb RAB and Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz

**Comment by CocoTheOwner** [comment]
Caused by the terrain of the lower biome to be pulled up despite having its height map height underneath ocean level. Iris then gets confused and places these plants. An easy fix would be to make a plugin-side setting that by default does not place any plants above the sea level. The way to resolve this on the plugin end is by raising the max generator height of the lower biome, and / or decreasing the min on the upper biome.

Please specify the biome names with `/ir std w b` so we know where to look.

**Comment by NextdoorPsycho** [comment]
I Believe this is working as of lately, reopen if its not
