### ISSUE TITLE
Strange path when generating

### ISSUE THREAD

**Issue by EneRGO22** [IrisDimensions/overworld#28]
Strange path when generating in the village dungeon
![2021-04-30_21 04 57](https://user-images.githubusercontent.com/68811273/118355327-0e90b680-b578-11eb-9d5d-2c20bf5fc5ec.png)
![2021-04-30_21 05 07](https://user-images.githubusercontent.com/68811273/118355331-14869780-b578-11eb-98f2-e08dc06ddfae.png)

**Comment by NextdoorPsycho** [comment]
this SHould be working now?
lmk if it is not

**Comment by cyberpwnn** [comment]
I smell Vacuum issues

**Comment by CocoTheOwner** [comment]
Follow your nose, you are right.

**Comment by CocoTheOwner** [comment]
This issue is not going to be resolved easily. The best way to mitigate issues such as this from happening is by not having biome connections that aren't in the same range (which causes a whole scala of issues in the world).
Vacuum is still iffy, but this should already happen a lot less often in the even the biome height does not vary strongly, when a village is placed ontop.
